{
 "title": "3Par Perf",
 "time": { "from": "2020-03-31T16:58:50.430Z", "to": "2020-04-02T13:07:57.868Z" },
 "templating": {
  "list": [
   { "name": "DS", "label": "DS", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "SCRATCH PANEL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "HOST" ], "type": "tag" },
      { "params": [ "PORT" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "VlunIo",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tmbpsavg" }
     ]
    }
   ]
  },
  { "title": "Host Ports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$DS Sum Host Port IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Total IOPS",
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tiocur" }
     ]
    },
    {
     "alias": "Read IOPS",
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "riocur" }
     ]
    },
    {
     "alias": "Write IOPS",
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "wiocur" }
     ]
    }
   ]
  },
  {
   "title": "$DS  Host Port Total iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "HostPort" ], "type": "tag" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tiocur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Sum Host Port MB/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "alias": "Host Port MB/s (Total)",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tmbpscur" }
     ]
    },
    {
     "alias": "Host Port MB/s (Read)",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "rmbpscur" }
     ]
    },
    {
     "alias": "Host Port MB/s (Write)",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "wmbpscur" }
     ]
    }
   ]
  },
  {
   "title": "$DS  Host Port IOsz (mean)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "Host Port Total IOsz (mean)",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tioszcur" }
     ]
    },
    {
     "alias": "Host Port Read IOsz (mean)",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "rioszcur" }
     ]
    },
    {
     "alias": "Host Port Write IOsz (mean)",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "wioszcur" }
     ]
    }
   ]
  },
  {
   "title": "$DS  Host Port Service Times ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Host Port Total Svt",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tsvtcur" }
     ]
    },
    {
     "alias": "Host Port Read Svt",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "rsvtcur" }
     ]
    },
    {
     "alias": "Host Port Write Svt",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "wsvtcur" }
     ]
    }
   ]
  },
  {
   "title": "$DS  Host Port Iops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "none", "label": "total iops" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "HostPort" ], "type": "tag" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tiocur" }
     ]
    }
   ]
  },
  {
   "title": "$DS  Host Port Qlen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "none", "label": "Qlen" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "HostPort" ], "type": "tag" }
     ],
     "measurement": "HostPortIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "qlen" }
     ]
    }
   ]
  },
  { "title": "Host Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "$DS Per Host Total IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "none", "label": "io" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "HOST" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tiocur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per Host Total MB/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "MBs", "label": "MB/s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "HOST" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tmbpscur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per Host Total IOsz (mean)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "deckbytes", "label": "KB" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "HOST" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tioszcur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per Host Qlen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "none", "label": "Qlen" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "HOST" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "qlen" }
     ]
    }
   ]
  },
  { "title": "VLUN Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "$DS Per VLUN Total IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "none", "label": "io" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "VLUN" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tiocur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per VLUN Read IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "none", "label": "io" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "VLUN" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "riocur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per VLUN Write IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "none", "label": "io" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "VLUN" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "wiocur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per VLUN Write MBps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "VLUN" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "wmbpscur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per VLUN Write IOSz (mean)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 116 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "VLUN" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "wioszcur" }
     ]
    }
   ]
  },
  {
   "title": "$DS VLUN Service Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 123 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Total Service Times",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tsvtcur" }
     ]
    },
    {
     "alias": "Read Service Times",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "rsvtcur" }
     ]
    },
    {
     "alias": "Write Service Times",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "wsvtcur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per VLUN Service Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Total Service Times",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "VLUN" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tsvtcur" }
     ]
    },
    {
     "alias": "Read Service Times",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "VLUN" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "rsvtcur" }
     ]
    },
    {
     "alias": "Write Service Times",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "VLUN" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "wsvtcur" }
     ]
    }
   ]
  },
  {
   "title": "$DS VLUN Qlen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "none", "label": "Qlen" }
   ],
   "targets": [
    {
     "alias": "Total Qlen",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "qlen" }
     ]
    }
   ]
  },
  { "title": "Combined Host/VLUN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "$DS Per Host / VLUN Total IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "none", "label": "io" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "HOST" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"HostIo\" WHERE (\"type\" = 'tiocur') AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tiocur" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "VLUN" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"HostIo\" WHERE (\"type\" = 'tiocur') AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tiocur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per Host / VLUN Total MB/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 152 },
   "yaxes": [
    { "format": "MBs", "label": "MB/s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "HOST" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"HostIo\" WHERE (\"type\" = 'tiocur') AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tmbpscur" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "VLUN" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"HostIo\" WHERE (\"type\" = 'tiocur') AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tmbpscur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per Host / VLUN mean IOsz",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "decmbytes", "label": "IOsz" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "HOST" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"HostIo\" WHERE (\"type\" = 'tiocur') AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tioszcur" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "VLUN" ], "type": "tag" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT \"value\" FROM \"HostIo\" WHERE (\"type\" = 'tiocur') AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tioszcur" }
     ]
    }
   ]
  },
  { "title": "VV Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 166 } },
  {
   "title": "$DS Sum VV IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 167 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Total IOPS",
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VvIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tiocur" }
     ]
    },
    {
     "alias": "Read IOPS",
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "riocur" }
     ]
    },
    {
     "alias": "Write IOPS",
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "VlunIo",
     "query": "SELECT value FROM \"Host\" WHERE \"type\" = 'rio' AND $timeFilter GROUP BY Host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "wiocur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per VV Total IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 174 },
   "yaxes": [
    { "format": "none", "label": "io" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "Vv" ], "type": "tag" }
     ],
     "measurement": "VvIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tiocur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per VV Read Service TImes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 181 },
   "yaxes": [
    { "format": "ms", "label": "service time" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "Vv" ], "type": "tag" }
     ],
     "measurement": "VvIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "rsvtcur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per VV Write Service TImes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 188 },
   "yaxes": [
    { "format": "ms", "label": "service time" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "Vv" ], "type": "tag" }
     ],
     "measurement": "VvIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "wsvtcur" }
     ]
    }
   ]
  },
  {
   "title": "$DS Per VV Total Service TImes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 195 },
   "yaxes": [
    { "format": "ms", "label": "service time" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "45s" ], "type": "time" },
      { "params": [ "Vv" ], "type": "tag" }
     ],
     "measurement": "VvIo",
     "query": "SELECT \"value\" FROM \"VlunIo\" WHERE \"type\" = 'tiocur'  AND $timeFilter GROUP BY VLUN",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tsvtcur" }
     ]
    }
   ]
  },
  { "title": "DelAck", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 } },
  {
   "title": "$DS Delayed Ack by Node/Tier",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 203 },
   "yaxes": [
    { "format": "none", "label": "DelAck" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "Node" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NodeDelAck",
     "query": "SELECT \"value\" FROM \"NodeDelAck\" WHERE \"type\" = 'ssd150delack' AND value >  0 AND $timeFilter GROUP BY Node",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "nldelack" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "Node" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NodeDelAck",
     "query": "SELECT \"value\" FROM \"NodeDelAck\" WHERE \"type\" = 'ssd150delack' AND value >  0 AND $timeFilter GROUP BY Node",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "fcdelack" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "Node" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NodeDelAck",
     "query": "SELECT \"value\" FROM \"NodeDelAck\" WHERE \"type\" = 'ssd150delack' AND value >  0 AND $timeFilter GROUP BY Node",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "ssd150delack" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "Node" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NodeDelAck",
     "query": "SELECT \"value\" FROM \"NodeDelAck\" WHERE \"type\" = 'ssd150delack' AND value >  0 AND $timeFilter GROUP BY Node",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "ssd100delack" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "Node" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NodeDelAck",
     "query": "SELECT \"value\" FROM \"NodeDelAck\" WHERE \"type\" = 'ssd150delack' AND value >  0 AND $timeFilter GROUP BY Node",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "ssddelack" }
     ]
    }
   ]
  },
  {
   "title": "$DS SSD Delayed Ack by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 210 },
   "yaxes": [
    { "format": "none", "label": "DelAck" }
   ],
   "targets": [
    {
     "alias": "Node0",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NodeDelAck",
     "query": "SELECT \"value\" FROM \"NodeDelAck\" WHERE \"type\" = 'ssd150delack' AND value >  0 AND $timeFilter GROUP BY Node",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "ssddelack" },
      { "condition": "AND", "key": "Node", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Node1",
     "groupBy": [
      { "params": [ "15s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "NodeDelAck",
     "query": "SELECT \"value\" FROM \"NodeDelAck\" WHERE \"type\" = 'ssd150delack' AND value >  0 AND $timeFilter GROUP BY Node",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "ssddelack" },
      { "condition": "AND", "key": "Node", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "$DS Delayed Ack changes by Node",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 217 },
   "yaxes": [
    { "format": "none", "label": "DelAck" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "Node" ], "type": "tag" }
     ],
     "measurement": "NodeDelAck",
     "query": "SELECT max(\"value\") FROM \"NodeDelAck\" WHERE (\"type\" = 'ssddelack' AND \"Node\" = '0') AND $timeFilter GROUP BY time(15s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "ssddelack" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "Node" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "NodeDelAck",
     "query": "SELECT max(\"value\") FROM \"NodeDelAck\" WHERE (\"type\" = 'ssddelack' AND \"Node\" = '0') AND $timeFilter GROUP BY time(15s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "ssd150delack" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "Node" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "NodeDelAck",
     "query": "SELECT max(\"value\") FROM \"NodeDelAck\" WHERE (\"type\" = 'ssddelack' AND \"Node\" = '0') AND $timeFilter GROUP BY time(15s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "ssd100delack" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "Node" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "NodeDelAck",
     "query": "SELECT max(\"value\") FROM \"NodeDelAck\" WHERE (\"type\" = 'ssddelack' AND \"Node\" = '0') AND $timeFilter GROUP BY time(15s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "fcdelack" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "Node" ], "type": "tag" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "NodeDelAck",
     "query": "SELECT max(\"value\") FROM \"NodeDelAck\" WHERE (\"type\" = 'ssddelack' AND \"Node\" = '0') AND $timeFilter GROUP BY time(15s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "nldelack" }
     ]
    }
   ]
  },
  { "title": "Combined Tier PD Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 224 } },
  {
   "title": "Total IOPs by Tier",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 225 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "TIER" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PdIo",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tiocur" }
     ]
    }
   ]
  },
  {
   "title": "Total MB/s by Tier",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 231 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "TIER" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PdIo",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tmbpscur" }
     ]
    }
   ]
  },
  {
   "title": "PD Service Times",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 237 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "TIER" ], "type": "tag" },
      { "params": [ "PD" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PdIo",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "tsvtcur" }
     ]
    }
   ]
  }
 ]
}