#!/bin/bash
echo "Use this script if creating new database."

read -p  'Enter DB Name: ' dbname

echo "Converting files"
dos2unix *

echo "Creating database $dbname"
influx -execute "CREATE DATABASE $dbname"

echo "Processing CPU counters"
statcpu_parse.awk statcpu* |split -l 500000 - cpu_
echo "Uploading CPU data to database $dbname"
for cpu in cpu_*;
do curl -i -XPOST 'http://127.0.0.1:8086/write?db='$dbname'&precision=s' --data-binary @$cpu
done

echo "Processing DelAck counters"
statcmp_parse.awk statcmp* |grep -v -e "---" |split -l 500000 - cmp_
echo "Uploading DelAck data to database $dbname"
for cmp in cmp_*;
do curl -i -XPOST 'http://127.0.0.1:8086/write?db='$dbname'&precision=s' --data-binary @$cmp
done

echo "Processing iscsi counters"
statiscsifull_parse.awk statiscsi-full* |split -l 500000 - iscsi_
echo "Uploading iSCSI data to database $dbname"
for iscsi in iscsi_*;
do curl -i -XPOST 'http://127.0.0.1:8086/write?db='$dbname'&precision=s' --data-binary @$iscsi
done

echo "Processing Host Port data"
statport-host_parse.awk statport*host* > hostport
echo "Uploading Host Port data to database $dbname"
curl -i -XPOST 'http://127.0.0.1:8086/write?db='$dbname'&precision=s' --data-binary @hostport

echo "Processing Disk Port data"
statport-disk_parse.awk statport*disk* > diskport
echo "Uploading Disk Port data to database $dbname"
curl -i -XPOST 'http://127.0.0.1:8086/write?db='$dbname'&precision=s' --data-binary @diskport

echo "Processing PD data"
statpd_parse.awk statpd* |split -l 500000 - pd_
echo "Uploading PD data to database $dbname"
for pd in pd_*;
do curl -i -XPOST 'http://127.0.0.1:8086/write?db='$dbname'&precision=s' --data-binary @$pd
done

echo "Processing VV data"
statvv_parse.awk statvv* |split -l 500000 - vv_
echo "Uploading VV data to database $dbname"
for vv in vv_*;
do curl -i -XPOST 'http://127.0.0.1:8086/write?db='$dbname'&precision=s' --data-binary @$vv
done

echo "Processing VLUN data"
statvlun_parse.awk statvlun* |split -l 500000 - vlun_
echo "Uploading VLUN data to database $dbname"
for vlun in vlun_*;
do curl -i -XPOST 'http://127.0.0.1:8086/write?db='$dbname'&precision=s' --data-binary @$vlun
done

echo "Processing RCVV data"
statrcvv_parse.awk statrcvv* |split -l 500000 - rcvv_
echo "Uploading RCVV data to database $dbname"
for rcvv in rcvv_*;
do curl -i -XPOST 'http://127.0.0.1:8086/write?db='$dbname'&precision=s' --data-binary @$rcvv
done

echo "Processing QoS data"
statqos_parse.awk statqos* |split -l 500000 - qos_
echo "Uploading QoS data to database $dbname"
for qos in qos_*;
do curl -i -XPOST 'http://127.0.0.1:8086/write?db='$dbname'&precision=s' --data-binary @$qos
done

echo "Processing histvlun data"
histvlun_parse.awk histvlun* |split -l 500000 - hv_
echo "Uploading histvlun data to database $dbname"
for hv in hv_*;
do curl -i -XPOST 'http://127.0.0.1:8086/write?db='$dbname'&precision=s' --data-binary @$hv
done

echo "Processing histpd data"
histpd_parse.awk histpd* |split -l 500000 - hp_
echo "Uploading histpd data to database $dbname"
for hp in hp_*;
do curl -i -XPOST 'http://127.0.0.1:8086/write?db='$dbname'&precision=s' --data-binary @$hp
done


echo "cleaning up..."
rm pd_* cpu_* diskport hostport vv_* vlun_* iscsi_* cmp_* rcvv_* qos_* hv_* hp_*
